version 1.0
EvgenyBelykh/java-filmorate pull request #1
Opened 2022-09-28 18:46 UTC by EvgenyBelykh

* первая версия программы

2022-09-29 09:43 UTC, EvgenyKoptubenko commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    public void addFilmWithEmptyName(){
пора начинать использовать параметризованные тесты, чтобы не было дублирования

2022-09-29 09:48 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    private int id;
Попробуй использовать так же другие аннотации @NotNull, @NotBlank, @Email

2022-09-29 09:54 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
ru.yandex.practicum.filmorate.exceptions.ValidationException: Фильм не может быть выпущен ранее: 1895-12-28
При этом ответ идет
{
	"timestamp": "2022-09-29T09:52:05.928+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/films"
}
Попробуй информацию об ошибках добавить в ответ. Предлагаю попробовать использовать Advice или просто в ответ засовывать сообщение об ошибке.

Это замечание из разряда "Можно лучше", т.е. необязательное

2022-09-29 09:57 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Есть предложения из разряда "Можно лучше". Если есть желание - поправь.
- Параметризованные тесты
- Сообщения об ошибках в ответах, чтобы не присылали клиенту просто 500

2022-09-29 20:30 UTC, EvgenyBelykh commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    public void addFilmWithEmptyName(){
С этим быстро разобраться не смог. Буду изучать.

2022-09-29 20:30 UTC, EvgenyBelykh commented on src/main/java/ru/yandex/practicum/filmorate/models/Film.java
> +    private int id;
Валидация полей добавил

2022-09-29 20:30 UTC, EvgenyBelykh commented on src/main/java/ru/yandex/practicum/filmorate/FilmorateApplication.java
> +	public static void main(String[] args) {
Быстро разобраться .что такое Advice, тоже не смог

2022-09-29 20:38 UTC, EvgenyBelykh commented
Версия 2.
*добавлена валидация полей

2022-09-30 16:50 UTC, EvgenyKoptubenko approved these changes
Основная часть задачи сделана хорошо. Замечания из разряда "параметризованные тесты" не обязательны. Принимаю. Спасибо за хорошую работу.

2022-09-30 18:38 UTC, merged