version 2
EvgenyBelykh/java-filmorate pull request #2
Opened 2022-10-13 18:39 UTC by EvgenyBelykh

* расширенный набор эндпоинтов
* добавлена логика добавления друзей
* добавлена логика выставления лайков фильмов

2022-10-13 20:20 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Можно в одном методе отлавливать сразу несколько эксепшенов 
@ExceptionHandler({ CustomException1.class, CustomException2.class })
https://www.baeldung.com/exception-handling-for-rest-with-spring

2022-10-13 20:26 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    public Film addFilm(@Valid @RequestBody Film film) {
curl --request POST \
  --url http://localhost:8080/films \
  --header 'Content-Type: application/json' \
  --data '{
	"name":"nameFilm2",
	"description":"film Description",
	"releaseDate":"2012-04-23T18:25:43.511Z",
	"duration":-1
}'

Попробуй сделать так, чтобы сообщение об ошибке не содержало стек трейс

{
	"error": "Validation failed for argument [0] in public ru.yandex.practicum.filmorate.models.Film ru.yandex.practicum.filmorate.controllers.FilmController.addFilm(ru.yandex.practicum.filmorate.models.Film): [Field error in object 'film' on field 'duration': rejected value [-1]; codes [Min.film.duration,Min.duration,Min.int,Min]; arguments [org.springframework.context.support.DefaultMessageSourceResolvable: codes [film.duration,duration]; arguments []; default message [duration],0]; default message [must be greater than or equal to 0]] "
}

2022-10-13 20:31 UTC, EvgenyKoptubenko commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ValidationException("Фильм - " + film.getName() + " c id - " + film.getId() + " уже есть в базе");
Если фильм с таким идентификатором уже есть в базе данных, то почему возвращается 404 ответ?
404 это ведь не найдено. А тут явно ошибка в отправляемых данных.
А если такой фильм уже есть, то может быть просто выдать ссылку на существующий фильм?

2022-10-13 20:32 UTC, EvgenyKoptubenko requested changes
Работа сделана очень хорошо. Замечаний практически нет. Попробуй настроить Idea так, чтобы во время коммита она сама убирала неиспользуемые импорты (если тебе такая функциональность будет удобна)

2022-10-16 12:21 UTC, EvgenyBelykh commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +            throw new ValidationException("Фильм - " + film.getName() + " c id - " + film.getId() + " уже есть в базе");
Тут исключение поставил другое, но боюсь, если поменять тело ответа, то не пройдет тест постмен

2022-10-16 12:25 UTC, EvgenyBelykh commented on src/main/java/ru/yandex/practicum/filmorate/controllers/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
Да, я знаю что так можно, но почему-то при объединении в логах вылезает много ошибок "WARN". Не смог разобраться из-за чего:
Так выглядело при объединении:
@ExceptionHandler({ValidationUserByIdException.class, ValidationFilmByIdException.class, MethodArgumentNotValidException.class })
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ErrorResponse handleValidationUserByIdException (RuntimeException e){
        return new ErrorResponse(e.getMessage());
    }

2022-10-17 08:57 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо

2022-10-17 18:36 UTC, merged